import type { Material, Partner } from '@/types/material'

export const MATERIALS: Material[] = [
  {
    id: 'HMB-001',
    name: '京都西陣 金襴帯地',
    nameEn: 'Kyoto Nishijin Kinran Obi Fabric',
    category: '帯地',
    materialType: '金襴織',
    color: '金系',
    pattern: '伝統文様',
    origin: '京都',
    era: '昭和',
    supplier: '西陣 辻村織物',
    quantity: 45,
    quantityUnit: 'm',
    quantitySize: 'medium',
    priceRange: 'high',
    status: 'public',
    recommendedUses: ['バッグ', 'インテリア', 'アート', '海外向け商品'],
    story: '西陣の織元が長年保管してきた金襴帯地。絹糸と金糸を織り込んだ重厚な質感があり、現代の商品開発でも強い存在感を出せる素材です。',
    characteristics: '張りと光沢があり、バッグ外装、額装、ホテル向けインテリア小物などに向いています。',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    tags: ['西陣', '金襴', '帯地', '絹', '金糸'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'origin', 'supplier', 'quantity'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'HMB-002',
    name: '大正期 正絹はぎれ',
    nameEn: 'Taisho Era Pure Silk Remnants',
    category: '古布',
    materialType: '正絹',
    color: '赤系',
    pattern: '花柄',
    origin: '京都',
    era: '大正',
    supplier: '京呉服 井筒屋',
    quantity: 12,
    quantityUnit: 'm',
    quantitySize: 'small',
    priceRange: 'premium',
    status: 'public',
    recommendedUses: ['スカーフ', 'アクセサリー', 'アート', 'クラウドファンディング'],
    story: '大正期の着物地として保管されていた正絹の古布。淡い赤と手描き風の花柄が特徴で、物語性のある限定商品に向いています。',
    characteristics: '薄手で柔らかく、スカーフ、ライナー、アクセサリーの差し色に適しています。',
    images: ['https://images.unsplash.com/photo-1580196969807-cc6de06c05be?w=1200', 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800'],
    tags: ['正絹', '大正', '花柄', '古布', '限定素材'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'supplier', 'quantity', 'materialType'],
    pendingFields: ['origin'],
    estimatedFields: ['story', 'pattern'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'HMB-003',
    name: '阿波藍染 木綿布',
    nameEn: 'Awa Indigo Dyed Cotton',
    category: '綿',
    materialType: '藍染木綿',
    color: '藍系',
    pattern: '無地',
    origin: '徳島',
    era: '昭和',
    supplier: '徳島 藍工房 佐々木',
    quantity: 80,
    quantityUnit: 'm',
    quantitySize: 'large',
    priceRange: 'mid',
    status: 'public',
    recommendedUses: ['アパレル', 'バッグ', 'インテリア', 'アップサイクル'],
    story: '阿波藍の染色技術を受け継ぐ工房に残っていた木綿布。深い藍色と経年による色の落ち着きが魅力です。',
    characteristics: '中厚手で縫製しやすく、アパレル、バッグ、クッションカバーなどに展開しやすい素材です。',
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    tags: ['藍染', '木綿', '徳島', '天然染料', '大ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'supplier', 'quantity', 'color'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: 'HMB-004',
    name: '結城紬 反物',
    nameEn: 'Yuki Tsumugi Silk Bolt',
    category: '反物',
    materialType: '紬',
    color: '茶系',
    pattern: '格子',
    origin: '茨城',
    era: '昭和',
    supplier: '結城 本田機業',
    quantity: 3,
    quantityUnit: '反',
    quantitySize: 'small',
    priceRange: 'premium',
    status: 'low_stock',
    recommendedUses: ['ジャケット裏地', 'バッグ', 'アクセサリー', 'アパレル'],
    story: '結城の機屋に保管されていた紬の反物。手仕事の節と落ち着いた格子柄があり、上質な小ロット商品に向いています。',
    characteristics: '軽さと独特の節感があり、ジャケット、バッグ内装、限定アクセサリーに活用できます。',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    tags: ['結城紬', '反物', '絹', '格子', '小ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'materialType', 'supplier', 'quantity'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'HMB-005',
    name: '越前和紙 楮繊維シート',
    nameEn: 'Echizen Washi Kozo Fiber Sheet',
    category: '和紙',
    materialType: '楮和紙',
    color: '白系',
    pattern: '無地',
    origin: '福井',
    era: '現代',
    supplier: '越前 和紙工房 山本',
    quantity: 40,
    quantityUnit: '点',
    quantitySize: 'medium',
    priceRange: 'mid',
    status: 'checking',
    recommendedUses: ['インテリア', 'アート', 'ノベルティ', '海外向け商品'],
    story: '越前和紙の工房で試作・保管されていた楮100%の繊維シート。透け感と繊維の表情があり、照明や什器まわりにも展開できます。',
    characteristics: '光を通す柔らかな質感。照明カバー、パッケージ、アートピースに向いています。',
    images: ['https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800'],
    tags: ['和紙', '越前', '楮', '照明', '工芸素材'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'materialType', 'supplier', 'quantity'],
    pendingFields: ['origin'],
    estimatedFields: ['story'],
    createdAt: '2024-03-12T00:00:00Z',
    updatedAt: '2024-03-28T00:00:00Z',
  },
  {
    id: 'HMB-006',
    name: '能登 生麻布',
    nameEn: 'Noto Natural Linen',
    category: '麻',
    materialType: '生麻布',
    color: '白系',
    pattern: '無地',
    origin: '石川',
    era: '現代',
    supplier: '能登 中村麻工房',
    quantity: 60,
    quantityUnit: 'm',
    quantitySize: 'large',
    priceRange: 'mid',
    status: 'public',
    recommendedUses: ['アパレル', 'インテリア', 'バッグ', 'アップサイクル'],
    story: '能登の工房が織った生成りの麻布。自然な風合いと通気性があり、サステナブルな商品企画と相性のよい素材です。',
    characteristics: 'やや張りがあり、洗いを重ねるほど柔らかくなります。シャツ、カーテン、バッグに向いています。',
    images: ['https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=1200', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'],
    tags: ['麻', '能登', '生成り', '天然素材', '大ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'origin', 'supplier', 'quantity', 'era'],
    pendingFields: [],
    estimatedFields: [],
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z',
  },
]

export const PARTNERS: Partner[] = [
  {
    id: 'P-001',
    name: '西陣 辻村織物',
    founded: '1892年創業',
    location: '京都府京都市上京区',
    speciality: '西陣織・金襴・帯地',
    story: '明治期から続く西陣の織元。市場縮小で眠っていた帯地や試作布を、現代のブランド開発へつなぐため素材バンクに参加しています。',
    materialCount: 1,
  },
  {
    id: 'P-002',
    name: '京呉服 井筒屋',
    founded: '1903年創業',
    location: '京都府京都市中京区',
    speciality: '正絹・反物・古布',
    story: '三代にわたり呉服素材を扱ってきた老舗。倉庫に眠る希少な古布を、現代のクリエイターへ届ける取り組みを進めています。',
    materialCount: 1,
  },
  {
    id: 'P-003',
    name: '徳島 藍工房 佐々木',
    founded: '1948年創業',
    location: '徳島県徳島市',
    speciality: '阿波藍染・木綿',
    story: '阿波藍の染色技術を継ぐ工房。保管布の活用先を広げ、藍染の価値を新しい商品に変換することを目指しています。',
    materialCount: 1,
  },
  {
    id: 'P-004',
    name: '越前 和紙工房 山本',
    founded: '1920年創業',
    location: '福井県越前市',
    speciality: '越前和紙・楮素材',
    story: '越前和紙の産地で100年以上続く工房。紙にとどまらない素材活用を、照明・内装・プロダクト領域へ広げています。',
    materialCount: 1,
  },
]
