import type { Material, Partner } from '@/types/material'

export const MATERIALS: Material[] = [
  {
    id: 'HMB-001',
    name: '京都西陣 金襴帯地',
    nameEn: 'Kyoto Nishijin Kinran Obi Fabric',
    category: '帯地',
    materialType: '金襴織',
    color: '金系',
    pattern: '伝統文様',
    origin: '京都',
    era: '昭和',
    supplier: '丸屋',
    quantity: 45,
    quantityUnit: 'm',
    quantitySize: 'medium',
    priceRange: 'high',
    status: 'public',
    recommendedUses: ['バッグ', 'インテリア', 'アート', '海外向け商品'],
    story: '西陣の織元が長年保管してきた金襴帯地。絹糸と金糸を織り込んだ重厚な質感があり、現代の商品開発でも強い存在感を出せる素材です。',
    characteristics: '張りと光沢があり、バッグ外装、額装、ホテル向けインテリア小物などに向いています。',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    tags: ['西陣', '金襴', '帯地', '絹', '金糸'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'origin', 'supplier', 'quantity'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-03-01T00:00:00Z',
  },
  {
    id: 'HMB-002',
    name: '大正期 正絹はぎれ',
    nameEn: 'Taisho Era Pure Silk Remnants',
    category: '古布',
    materialType: '正絹',
    color: '赤系',
    pattern: '花柄',
    origin: '京都',
    era: '大正',
    supplier: '丸屋',
    quantity: 12,
    quantityUnit: 'm',
    quantitySize: 'small',
    priceRange: 'premium',
    status: 'public',
    recommendedUses: ['スカーフ', 'アクセサリー', 'アート', 'クラウドファンディング'],
    story: '大正期の着物地として保管されていた正絹の古布。淡い赤と手描き風の花柄が特徴で、物語性のある限定商品に向いています。',
    characteristics: '薄手で柔らかく、スカーフ、ライナー、アクセサリーの差し色に適しています。',
    images: ['https://images.unsplash.com/photo-1580196969807-cc6de06c05be?w=1200', 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800'],
    tags: ['正絹', '大正', '花柄', '古布', '限定素材'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'supplier', 'quantity', 'materialType'],
    pendingFields: ['origin'],
    estimatedFields: ['story', 'pattern'],
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-02-20T00:00:00Z',
  },
  {
    id: 'HMB-003',
    name: '阿波藍染 木綿布',
    nameEn: 'Awa Indigo Dyed Cotton',
    category: '綿',
    materialType: '藍染木綿',
    color: '藍系',
    pattern: '無地',
    origin: '徳島',
    era: '昭和',
    supplier: '丸屋',
    quantity: 80,
    quantityUnit: 'm',
    quantitySize: 'large',
    priceRange: 'mid',
    status: 'public',
    recommendedUses: ['アパレル', 'バッグ', 'インテリア', 'アップサイクル'],
    story: '阿波藍の染色技術を受け継ぐ工房に残っていた木綿布。深い藍色と経年による色の落ち着きが魅力です。',
    characteristics: '中厚手で縫製しやすく、アパレル、バッグ、クッションカバーなどに展開しやすい素材です。',
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    tags: ['藍染', '木綿', '徳島', '天然染料', '大ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'supplier', 'quantity', 'color'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-03-05T00:00:00Z',
  },
  {
    id: 'HMB-004',
    name: '結城紬 反物',
    nameEn: 'Yuki Tsumugi Silk Bolt',
    category: '反物',
    materialType: '紬',
    color: '茶系',
    pattern: '格子',
    origin: '茨城',
    era: '昭和',
    supplier: '丸屋',
    quantity: 3,
    quantityUnit: '反',
    quantitySize: 'small',
    priceRange: 'premium',
    status: 'low_stock',
    recommendedUses: ['ジャケット裏地', 'バッグ', 'アクセサリー', 'アパレル'],
    story: '結城の機屋に保管されていた紬の反物。手仕事の節と落ち着いた格子柄があり、上質な小ロット商品に向いています。',
    characteristics: '軽さと独特の節感があり、ジャケット、バッグ内装、限定アクセサリーに活用できます。',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    tags: ['結城紬', '反物', '絹', '格子', '小ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'materialType', 'supplier', 'quantity'],
    pendingFields: ['era'],
    estimatedFields: ['story'],
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-03-10T00:00:00Z',
  },
  {
    id: 'HMB-005',
    name: '越前和紙 楮繊維シート',
    nameEn: 'Echizen Washi Kozo Fiber Sheet',
    category: '和紙',
    materialType: '楮和紙',
    color: '白系',
    pattern: '無地',
    origin: '福井',
    era: '現代',
    supplier: '丸屋',
    quantity: 40,
    quantityUnit: '点',
    quantitySize: 'medium',
    priceRange: 'mid',
    status: 'checking',
    recommendedUses: ['インテリア', 'アート', 'ノベルティ', '海外向け商品'],
    story: '越前和紙の工房で試作・保管されていた楮100%の繊維シート。透け感と繊維の表情があり、照明や什器まわりにも展開できます。',
    characteristics: '光を通す柔らかな質感。照明カバー、パッケージ、アートピースに向いています。',
    images: ['https://images.unsplash.com/photo-1544967082-d9d25d867d66?w=1200', 'https://images.unsplash.com/photo-1590736704728-f4730bb30770?w=800'],
    tags: ['和紙', '越前', '楮', '照明', '工芸素材'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'materialType', 'supplier', 'quantity'],
    pendingFields: ['origin'],
    estimatedFields: ['story'],
    createdAt: '2024-03-12T00:00:00Z',
    updatedAt: '2024-03-28T00:00:00Z',
  },
  {
    id: 'HMB-006',
    name: '能登 生麻布',
    nameEn: 'Noto Natural Linen',
    category: '麻',
    materialType: '生麻布',
    color: '白系',
    pattern: '無地',
    origin: '石川',
    era: '現代',
    supplier: '丸屋',
    quantity: 60,
    quantityUnit: 'm',
    quantitySize: 'large',
    priceRange: 'mid',
    status: 'public',
    recommendedUses: ['アパレル', 'インテリア', 'バッグ', 'アップサイクル'],
    story: '能登の工房が織った生成りの麻布。自然な風合いと通気性があり、サステナブルな商品企画と相性のよい素材です。',
    characteristics: 'やや張りがあり、洗いを重ねるほど柔らかくなります。シャツ、カーテン、バッグに向いています。',
    images: ['https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=1200', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800'],
    tags: ['麻', '能登', '生成り', '天然素材', '大ロット'],
    sampleAvailable: true,
    isFeatured: false,
    verifiedFields: ['category', 'origin', 'supplier', 'quantity', 'era'],
    pendingFields: [],
    estimatedFields: [],
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-03-08T00:00:00Z',
  },
  {
    id: 'HMB-007',
    name: '正絹100% 帯地',
    nameEn: 'Pure Silk Obi Fabric',
    category: '帯地',
    materialType: '正絹100%',
    color: '白系',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['バッグ', 'インテリア', 'アート', 'アクセサリー'],
    story: '淡い地色に繊細な織り柄と控えめな色柄が入った正絹100%の帯地。上品な光沢と和の表情があり、限定商品や一点物の企画に向いています。',
    characteristics: '正絹ならではのしなやかさと光沢があり、バッグ小物、額装、インテリアアクセント、アクセサリー素材として活用できます。',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    tags: ['丸屋', '帯地', '正絹100%', '絹', '伝統文様'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'supplier', 'materialType'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-14T00:00:00Z',
    updatedAt: '2026-05-14T00:00:00Z',
  },
  {
    id: 'HMB-008',
    name: '正絹100% 訪問着用帯 01',
    nameEn: 'Pure Silk Obi for Homongi 01',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-008/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-009',
    name: '正絹100% 訪問着用帯 02',
    nameEn: 'Pure Silk Obi for Homongi 02',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-009/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-010',
    name: '正絹100% 訪問着用帯 03',
    nameEn: 'Pure Silk Obi for Homongi 03',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-010/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-011',
    name: '正絹100% 訪問着用帯 04',
    nameEn: 'Pure Silk Obi for Homongi 04',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-011/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-012',
    name: '正絹100% 訪問着用帯 05',
    nameEn: 'Pure Silk Obi for Homongi 05',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-012/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-013',
    name: '正絹100% 訪問着用帯 06',
    nameEn: 'Pure Silk Obi for Homongi 06',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-013/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-014',
    name: '正絹100% 訪問着用帯 07',
    nameEn: 'Pure Silk Obi for Homongi 07',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-014/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-015',
    name: '正絹100% 訪問着用帯 08',
    nameEn: 'Pure Silk Obi for Homongi 08',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-015/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-016',
    name: '正絹100% 訪問着用帯 09',
    nameEn: 'Pure Silk Obi for Homongi 09',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-016/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-017',
    name: '正絹100% 訪問着用帯 10',
    nameEn: 'Pure Silk Obi for Homongi 10',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-017/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-018',
    name: '正絹100% 訪問着用帯 11',
    nameEn: 'Pure Silk Obi for Homongi 11',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-018/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-019',
    name: '正絹100% 訪問着用帯 12',
    nameEn: 'Pure Silk Obi for Homongi 12',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-019/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-020',
    name: '正絹100% 訪問着用帯 13',
    nameEn: 'Pure Silk Obi for Homongi 13',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-020/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-021',
    name: '正絹100% 訪問着用帯 14',
    nameEn: 'Pure Silk Obi for Homongi 14',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-021/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-022',
    name: '正絹100% 訪問着用帯 15',
    nameEn: 'Pure Silk Obi for Homongi 15',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-022/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-023',
    name: '正絹100% 訪問着用帯 16',
    nameEn: 'Pure Silk Obi for Homongi 16',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-023/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-024',
    name: '正絹100% 訪問着用帯 17',
    nameEn: 'Pure Silk Obi for Homongi 17',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-024/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-025',
    name: '正絹100% 訪問着用帯 18',
    nameEn: 'Pure Silk Obi for Homongi 18',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-025/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-026',
    name: '正絹100% 訪問着用帯 19',
    nameEn: 'Pure Silk Obi for Homongi 19',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-026/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },]

export const PARTNERS: Partner[] = [
  {
    id: 'P-001',
    name: '丸屋',
    founded: '素材提供元',
    location: '日本',
    speciality: '伝統素材・職人工房の素材活用',
    story: '丸屋は、伝統素材や職人の技術を受け継ぎながら、現代のものづくりへつなぐ素材提供元です。素材の背景や活用可能性を整理し、商品開発や共創の入口をつくります。',
    materialCount: MATERIALS.length,
    websiteUrl: 'https://haruka-llc.com/partners/maruya',
  },
]
