import type { Material, Partner } from '@/types/material'

export const MATERIALS: Material[] = [
  {
    id: 'HMB-008',
    name: '正絹100% 訪問着用帯 01',
    nameEn: 'Pure Silk Obi for Homongi 01',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-008/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-009',
    name: '正絹100% 訪問着用帯 02',
    nameEn: 'Pure Silk Obi for Homongi 02',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-009/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-010',
    name: '正絹100% 訪問着用帯 03',
    nameEn: 'Pure Silk Obi for Homongi 03',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-010/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-011',
    name: '正絹100% 訪問着用帯 04',
    nameEn: 'Pure Silk Obi for Homongi 04',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-011/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-012',
    name: '正絹100% 訪問着用帯 05',
    nameEn: 'Pure Silk Obi for Homongi 05',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-012/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-013',
    name: '正絹100% 訪問着用帯 06',
    nameEn: 'Pure Silk Obi for Homongi 06',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-013/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-014',
    name: '正絹100% 訪問着用帯 07',
    nameEn: 'Pure Silk Obi for Homongi 07',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-014/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-015',
    name: '正絹100% 訪問着用帯 08',
    nameEn: 'Pure Silk Obi for Homongi 08',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-015/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-016',
    name: '正絹100% 訪問着用帯 09',
    nameEn: 'Pure Silk Obi for Homongi 09',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-016/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-017',
    name: '正絹100% 訪問着用帯 10',
    nameEn: 'Pure Silk Obi for Homongi 10',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-017/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-018',
    name: '正絹100% 訪問着用帯 11',
    nameEn: 'Pure Silk Obi for Homongi 11',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-018/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-019',
    name: '正絹100% 訪問着用帯 12',
    nameEn: 'Pure Silk Obi for Homongi 12',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-019/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-020',
    name: '正絹100% 訪問着用帯 13',
    nameEn: 'Pure Silk Obi for Homongi 13',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-020/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-021',
    name: '正絹100% 訪問着用帯 14',
    nameEn: 'Pure Silk Obi for Homongi 14',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-021/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-022',
    name: '正絹100% 訪問着用帯 15',
    nameEn: 'Pure Silk Obi for Homongi 15',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-022/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-023',
    name: '正絹100% 訪問着用帯 16',
    nameEn: 'Pure Silk Obi for Homongi 16',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-023/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-024',
    name: '正絹100% 訪問着用帯 17',
    nameEn: 'Pure Silk Obi for Homongi 17',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-024/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-025',
    name: '正絹100% 訪問着用帯 18',
    nameEn: 'Pure Silk Obi for Homongi 18',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-025/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },  {
    id: 'HMB-026',
    name: '正絹100% 訪問着用帯 19',
    nameEn: 'Pure Silk Obi for Homongi 19',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: 'その他',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '正絹100%の訪問着用帯。意匠の異なる一点物として、柄や色味を活かした相談ができる素材です。',
    characteristics:
      '訪問着用の帯として仕立てられた正絹素材。繊細な光沢と柄の表情があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-026/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '訪問着用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-18T00:00:00Z',
    updatedAt: '2026-05-18T00:00:00Z',
  },
  {
    id: 'HMB-027',
    name: '正絹100% 成人式用帯 01',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 01',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '赤と金を基調に、梅や亀甲、波文様が重なる正絹100%の成人式用帯。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と祝い柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-027/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '伝統文様'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-028',
    name: '正絹100% 成人式用帯 02',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 02',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '花柄',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '黒と紫の地色に、金の桜文様が配された正絹100%の成人式用帯。落ち着きと華やかさをあわせ持つ一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。深い地色と金糸の花柄が特徴で、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-028/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '花柄'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-029',
    name: '正絹100% 成人式用帯 03',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 03',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-029/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-030',
    name: '正絹100% 成人式用帯 04',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 04',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-030/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-031',
    name: '正絹100% 成人式用帯 05',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 05',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-031/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-032',
    name: '正絹100% 成人式用帯 06',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 06',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-032/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-033',
    name: '正絹100% 成人式用帯 07',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 07',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-033/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-034',
    name: '正絹100% 成人式用帯 08',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 08',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-034/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-035',
    name: '正絹100% 成人式用帯 09',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 09',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-035/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-036',
    name: '正絹100% 成人式用帯 10',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 10',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-036/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-037',
    name: '正絹100% 成人式用帯 11',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 11',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-037/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-038',
    name: '正絹100% 成人式用帯 12',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 12',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-038/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-039',
    name: '正絹100% 成人式用帯 13',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 13',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-039/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-040',
    name: '正絹100% 成人式用帯 14',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 14',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-040/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-041',
    name: '正絹100% 成人式用帯 15',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 15',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-041/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-042',
    name: '正絹100% 成人式用帯 16',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 16',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-042/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-043',
    name: '正絹100% 成人式用帯 17',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 17',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-043/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-044',
    name: '正絹100% 成人式用帯 18',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 18',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-044/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-045',
    name: '正絹100% 成人式用帯 19',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 19',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-045/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-046',
    name: '正絹100% 成人式用帯 20',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 20',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-046/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-047',
    name: '正絹100% 成人式用帯 21',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 21',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-047/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-048',
    name: '正絹100% 成人式用帯 22',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 22',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-048/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-049',
    name: '正絹100% 成人式用帯 23',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 23',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-049/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
  {
    id: 'HMB-050',
    name: '正絹100% 成人式用帯 24',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 24',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-050/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },

  {
    id: 'HMB-052',
    name: '正絹100% 成人式用帯 26',
    nameEn: 'Pure Silk Obi for Coming-of-Age Ceremony 26',
    category: '帯地',
    materialType: '正絹100%',
    color: '多色',
    pattern: '伝統文様',
    origin: '日本',
    era: '不明',
    supplier: '丸屋',
    quantity: 1,
    quantityUnit: '点',
    quantitySize: 'single',
    priceRange: 'consult',
    status: 'checking',
    recommendedUses: ['アート', 'アクセサリー'],
    story:
      '成人式用の帯として仕立てられた正絹100%の帯地。華やかな意匠を活かした一点物素材です。',
    characteristics:
      '成人式用の帯として仕立てられた正絹素材。金糸の光沢と柄の存在感があり、和装用途に加え、意匠を活かした企画素材としても相談できます。',
    images: ['/materials/HMB-052/main.jpg'],
    tags: ['丸屋', '帯地', '正絹100%', '成人式用帯', '一点物'],
    sampleAvailable: true,
    isFeatured: true,
    verifiedFields: ['category', 'materialType', 'supplier'],
    pendingFields: ['origin', 'era', 'quantity'],
    estimatedFields: ['story', 'pattern', 'color'],
    createdAt: '2026-05-21T00:00:00Z',
    updatedAt: '2026-05-21T00:00:00Z',
  },
]

export const PARTNERS: Partner[] = [
  {
    id: 'P-001',
    name: '丸屋',
    founded: '素材提供元',
    location: '日本',
    speciality: '伝統素材・職人工房の素材活用',
    story: '丸屋は、伝統素材や職人の技術を受け継ぎながら、現代のものづくりへつなぐ素材提供元です。素材の背景や活用可能性を整理し、商品開発や共創の入口をつくります。',
    materialCount: MATERIALS.length,
    websiteUrl: 'https://haruka-llc.com/partners/maruya',
  },
]
